language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cd "${TRAVIS_BUILD_DIR}"
  - cargo build
  - cargo build --all-features
  - cargo test --all-features